online_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    # Custom
    path('', include('store.urls')),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.books, name='books'),
    path('cart/', views.cart, name='cart'),
    path('old_cart/<int:cart_id>/', views.old_cart, name='old_cart'),
    path('edit_book/<int:book_id>/', views.edit_book, name='edit_book'),
    path('buy_book/<int:book_id>/', views.buy_book, name='buy_book'),
    path('details/<int:book_id>/', views.details, name='details'),
    path('delete_book_order/<int:book_order_id>/', views.delete_book_order, name='delete_book_order'),
    path('checkout/', views.checkout, name='checkout'),
    path('add_order/', views.add_order, name='add_order'),
    path('orders/', views.orders, name='orders'),
    path('about_page/', views.about_page, name='about_page'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

store/models.py
from django.contrib.auth.models import User
from django.db import models


class Author(models.Model):
    """An entity that describes an author."""

    name = models.CharField(max_length=100, default=None)
    surname = models.CharField(max_length=100, default=None)

    def __str__(self):
        return self.name + ' ' + self.surname


class Category(models.Model):
    """A model which describes the genre of a book. E.G. Drama, Comedy..."""

    name = models.CharField(max_length=200)
    is_child = models.BooleanField(default=True)  # It means this category is not parent
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Book(models.Model):
    """
    A model which describes the book entity. Each Book has a
    foreign key referencing the ID of a Category.
    """

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, editable=True)
    title = models.CharField(max_length=200)
    price = models.FloatField(default=0.0)

    quantity = models.IntegerField(default=50)
    date_added = models.DateTimeField(auto_now_add=True)
    first_published = models.IntegerField(default=1900)
    description = models.TextField(max_length=500)
    url = models.URLField(
        default='https://digitalsynopsis.com/wp-content/uploads/2016/06/negative-space-design-art-illustration-ads-30.jpg')

    class Meta:
        verbose_name_plural = 'books'

    def __str__(self):
        return self.title + ' By ' + str(self.author)


class BookOrder(models.Model):
    """A model which holds the relation between the quantity and the purchased book."""
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    # Calculate price of all books together.
    def price(self):
        return self.book.price * self.quantity


class Cart(models.Model):
    """A model which describes the book list before purchasing."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    book_orders = models.ManyToManyField(BookOrder, editable=True)

    def total(self):
        total = 0.0
        for book_order in self.book_orders.all():
            total = total + book_order.price()
        return total

    def can_buy(self):
        """
        Checks if there are any out of stock books.

        :return: False if purchase unavailable.
        """
        for book_order in self.book_orders.all():
            if book_order.quantity > book_order.book.quantity:
                return False
        return True


class OrderContact(models.Model):
    """A model which describes an address and other contact info."""

    class Meta:
        verbose_name_plural = 'contacts'

    street = models.CharField(max_length=200)
    number = models.IntegerField()
    city = models.CharField(max_length=200)
    bl = models.CharField(max_length=50, null=True, blank=True)
    sc = models.CharField(max_length=50, null=True, blank=True)
    ap = models.CharField(max_length=50, null=True, blank=True)
    county = models.CharField(max_length=200)
    phone = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.street + ' ' + str(self.number) + ', ' + self.city


class Order(models.Model):
    """A model which describes a previous purchase."""

    class Meta:
        verbose_name_plural = 'orders'

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    contact = models.ForeignKey(OrderContact, on_delete=models.DO_NOTHING)
    date_added = models.DateTimeField(auto_now_add=True)

store/forms.py
from django import forms
from .models import Book, OrderContact


class BookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)

        instance = getattr(self, 'instance', None)

        if instance and instance.id:
            self.fields['title'].widget.attrs['readonly'] = True
            self.fields['author'].widget.attrs['readonly'] = True
            self.fields['price'].widget.attrs['readonly'] = True
            self.fields['category'].widget.attrs['readonly'] = True

    class Meta:
        model = Book
        fields = ['title', 'author', 'price', 'category']
        labels = {'title': 'Title',
                  'author': 'Author',
                  'price': 'Price',
                  'category': 'Category'}


class OrderContactForm(forms.ModelForm):
    class Meta:
        model = OrderContact
        fields = ['street', 'number', 'city', 'bl', 'sc', 'ap', 'county', 'phone', 'email']
        labels = {'street': 'Street',
                  'number': 'Nr.',
                  'city': 'City',
                  'bl': 'Bl. (Optional)',
                  'sc': 'Sc. (Optional)',
                  'ap': 'Ap. (Optional)',
                  'county': 'County',
                  'phone': 'Contact Phone',
                  'email': 'Email (Optional)'}

store/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import Http404
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist

from store.forms import BookForm, OrderContactForm
from store.models import Book, Category, BookOrder, Cart, OrderContact, Order


def index(request):
    context = {
        'header': ''
    }
    return render(request, 'store/index.html', context)


def cart(request):
    try:
        cart_obj = Cart.objects.get(owner=request.user)
    except ObjectDoesNotExist:
        Cart.objects.create(owner=request.user)
        cart_obj = Cart.objects.get(owner=request.user)

    context = {
        "cart": cart_obj
    }
    return render(request, 'store/cart.html', context)


def old_cart(request, cart_id):
    try:
        cart_obj = Cart.objects.get(pk=cart_id)
    except ObjectDoesNotExist:
        raise Http404

    context = {
        "cart": cart_obj
    }
    return render(request, 'store/cart.html', context)


def books(request):
    """Show all available books."""

    book_list: [] = Book.objects.all().order_by('date_added')
    category_list: [] = Category.objects.all()

    context = {
        "books": book_list,
        "categories": category_list
    }
    return render(request, 'store/books.html', context)


def add_to_order(request, book_id):
    cart_obj = Cart.objects.get(owner=request.user)
    quantity = int(request.POST['quantity'])

    # Increment the quantity for existing book in cart.
    for book_order in cart_obj.book_orders.all():
        if book_order.book.id == book_id:
            book_order.quantity = book_order.quantity + quantity
            book_order.save()
            return

    # Create new book order and add it to cart.
    book = Book.objects.get(pk=book_id)
    book_order = BookOrder.objects.create(book=book, quantity=quantity)
    cart_obj.book_orders.add(book_order)


@login_required
def buy_book(request, book_id):
    """
    Create new cart if there isn't one created yet.
    If there is a cart, add the book to it's list of book id's.
    :param quantity:
    :param request:
    :param book_id:
    :return: Redirects to books screen
    """

    try:
        add_to_order(request, book_id)
    except ObjectDoesNotExist:
        Cart.objects.create(owner=request.user)
        add_to_order(request, book_id)

    return redirect('/books/')


@login_required
def delete_book_order(request, book_order_id):
    BookOrder.objects.get(pk=book_order_id).delete()
    return redirect('/cart/')


@login_required
def checkout(request):
    form = OrderContactForm()

    context = {
        'form': form
    }
    return render(request, 'store/checkout.html', context)


@login_required
def orders(request):
    orders_obj = Order.objects.filter(owner=request.user)

    context = {
        'orders': orders_obj
    }
    return render(request, 'store/orders.html', context)


@login_required
@transaction.atomic()
def add_order(request):
    cart_obj = Cart.objects.get(owner=request.user)

    order_contact = OrderContact.objects.create(
        street=request.POST['street'],
        number=request.POST['number'],
        city=request.POST['city'],
        bl=request.POST['bl'],
        sc=request.POST['sc'],
        ap=request.POST['ap'],
        county=request.POST['county'],
        phone=request.POST['phone'],
        email=request.POST['email']
    )

    Order.objects.create(
        owner=request.user,
        cart=cart_obj,
        contact=order_contact
    )

    # Decrement the quantity of remained books to purchase.
    for book_order in cart_obj.book_orders.all():
        book = book_order.book

        if book.quantity < book_order.quantity:
            raise Http404

        book.quantity = book.quantity - book_order.quantity
        book.save()

    # Remove owner from the cart. This will make the app create another cart in case of a new purchase.
    # The purchased carts will still exist.
    cart_obj.owner = None
    cart_obj.save()

    return redirect('/books/')


def check_owner(model, request):
    """Raise exception if the punishment does not belong to current user."""
    if model.owner != request.user:
        raise Http404


def details(request, book_id):
    context = {'book': Book.objects.get(id=book_id)}

    return render(request, 'store/details.html', context)


@login_required
def edit_book(request, book_id):
    """Edit book by given id. used by admin."""
    book_obj = Book.objects.get(id=book_id)

    if request.method != 'POST':
        # Initial request, fill form with current punishment data.
        form = BookForm(instance=book_obj)
    else:
        # Post data submitted.
        form = BookForm(instance=book_obj, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('store:index')

    # It means the form was just opened and must be loaded, not saved.
    context = {'book': book_obj, 'form': form}
    return render(request, 'store/edit_book.html', context)


def about_page(request):
    context = {'header': 'About this page'}
    return render(request, 'store/about.html', context)

templates/store/about.html
{% extends "store/base.html" %}
{% block content %}
    <div class="jumbotron jumbotron-fluid" style="background-color: #B22222; color: white">
        <div class="container" style="display: inline-flex">
            <h1 class="display-4">About Online Book Store</h1> <img
                src="https://media.istockphoto.com/photos/stack-of-colorful-hardback-books-open-book-on-blue-background-picture-id506432952?k=6&m=506432952&s=170667a&w=0&h=BXwQ2ggyC-oG-Ivxv9dfyREFxCFz4n7YDlkZfYHs3xU=" class="img-thumbnail mx-auto" alt=""
                style="width: 100px">
        </div>
        <div class="jumbotron jumbotron-fluid" style="background-color: white; color: dimgrey">
            <div class="container">
                <p style="font-family:Cli; font-size: large; ">
                <ul>
                    <li>Online Book store is an online web application where
                        the customer can purchase books online.
                    </li>
                    <br>
                    <li> Through a web browser the customers can search for
                        a book by its title or author, later can add to the shopping cart and finally purchase the
                        books.
{#                        By which user can put details of books and user can search it.#}
                    </li>
                    <br>
                    <li>The Online Book Store application enables vendor to setup online book store, customers to
                        browse.
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

templates/store/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Online Book Store</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now "U" %}'"/>
</head>

<body class="main-background" style="background-color: Gainsboro">
<nav class="navbar navbar-expand-md bg-white navbar-light border">
    <div>
        <a style="color: grey; font-size: x-large;" class="navbar-brand" href="{% url 'store:index' %}">
            O<span class="application-color">nline</span>
            B<span class="application-color">ook</span>
            S<span class="application-color">tore</span></a>
        {#        <span class="small bg-dark p-0" style="margin-left: -20px; color: white">v1.0</span>#}
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">

        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Logged as {{ user.username }}</span>
                </li>
            {% endif %}
            <li class="nav-item mx-1">
                <a class="btn btn-outline-danger" href="{% url 'store:index' %}">Home</a>
            </li>
            <li class="nav-item mx-1">
                <a class="btn btn-outline-danger" href="{% url 'store:books' %}">Products</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item mx-1">
                    <a class="btn btn-outline-danger" href="{% url 'store:cart' %}">Cart</a>
                </li>
                <li class="nav-item mx-1">
                    <a class="btn btn-outline-danger" href="{% url 'store:orders' %}">Orders</a>
                </li>
                <li class="nav-item mx-1">
                    <a class="btn btn-outline-danger" href="{% url 'store:about_page' %}">About</a>
                </li>
                <li class="nav-item mx-1">
                    <a class="btn btn-outline-danger" href="{% url 'users:logout' %}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="btn btn-outline-danger" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-danger" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<main role="main" class="container">
    <div class="container">
        <div class="justify-content-center">
            {% block content %}

            {% endblock content %}
        </div>
    </div>
</main>
</body>
</html>

templates/store/books.html
{% extends "store/base.html" %}

{% block content %}
    {% for category in categories %}
        <div class="row text-center justify-content-center" style="border-bottom: #B22222 1px dashed">
            {% if category.name == 'Fiction' or category.name == 'Nonfiction' %}
                <h1 class="display-5 mr-auto mx-auto" style="color: black; font-weight: bolder"><< {{ category.name }}
                    >></h1>
            {% else %}
                <h1 class="display-5 mr-auto mx-auto" style="color: #B22222">{{ category.name }}</h1>
            {% endif %}
            <div class="scroll-menu container-fluid">

                {% for book in books %}
                    {% if category in book.category.all %}
                        <a href="{% url 'store:details' book.id %}">
                            <img class="zoom-image m-2" src="{{ book.url }}"
                                 alt="Card image cap" title={{ book.title }}>
                        </a>
                    {% endif %}
                {% empty %}
                    <p>No books to display for this category...</p>
                {% endfor %}
            </div>
        </div>
    {% empty %}
        <p>No categories...</p>
    {% endfor %}
{% endblock content %}

templates/store/cart.html
{% extends "store/base.html" %}

{% block content %}
    {% if cart.total > 0 %}
        <div class="row mt-2">
            {% if cart.owner %}
                <div class="col">
                    <h1 class="display-5 mb-2">Total: ${{ cart.total|floatformat:2 }}</h1>
                </div>
                {% if cart.can_buy %}
                    <a class="btn btn-success h-50 my-auto" href="{% url 'store:checkout' %}">To Checkout</a>
                {% endif %}
            {% else %}
                <div class="col">
                    <h1 class="display-5 mb-2">Total payed: ${{ cart.total }}</h1>
                </div>
            {% endif %}
        </div>
    {% endif %}

    {% for book_order in cart.book_orders.all %}
        <div class="row bg-white my-3 py-2">
            <div class="col">
                <a href="{% url 'store:details' book_order.book.id %}">
                    <img class="zoom-image m-2" src="{{ book_order.book.url }}"
                         alt="Card image cap" title={{ book_order.book.title }}>
                </a>
            </div>
            <div class="col">
                <p><span style="font-weight: bold">Title:</span> {{ book_order.book }}</p>
                <p><span style="font-weight: bold">Author:</span> {{ book_order.book.author }}</p>
                <p><span style="font-weight: bold">Quantity:</span> {{ book_order.quantity }}
                    {% if cart.owner %}
                        {% if book_order.quantity > book_order.book.quantity %}
                            [
                            <span style="font-weight: bold; color: #B22222">{{ book_order.book.quantity }} book(s) left</span>
                            ]
                        {% else %}
                            [<span style="font-weight: bold;">{{ book_order.book.quantity }} book(s) left</span>]
                        {% endif %}
                    {% endif %}
                </p>
                <p><span style="font-weight: bold">Cost:</span> ${{ book_order.price }}</p>

                {% if cart.owner %}
                    <form action="{% url 'store:delete_book_order' book_order.id %}" class="form" method="post">
                        {% csrf_token %}

                        <button type="submit" class="btn btn-danger">Remove
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
    {% empty %}
        <p>Nothing added to cart...</p>
    {% endfor %}
    <div class="mb-3"></div>
{% endblock content %}

templates/store/checkout.html
{% extends "store/base.html" %}
{% load bootstrap4 %}

{% block content %}
      <div class="row justify-content-center order-form">
        <div class="bg-white p-5 col-12 col-sm-10 col-md-8 col-lg-5 bg-light">

            <h1 class="display-4 text-center">Order Form</h1>

            <form method="post" action="{% url 'store:add_order' %}">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <div class="col-md-12 text-center">
                        <button class="btn btn-primary text-center" style="width: 100px;" name="submit">Order</button>
                    </div>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock content %}

templates/store/details.html
{% extends "store/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container my-2">
        <div class="row">
            <div class="col mx-auto">
                <div class="card shadow">
                    <div class="row">
                        <div class="col-12 col-lg-5 ml-2 mt-2">
                            <img class="image-details" src={{ book.url }}>
                        </div>

                        <div class="col-12 col-lg-6 ml-2 mt-2">
                            <h5 class="card-title">{{ book.title }}</h5>
                            <p class="card-text">Price: ${{ book.price }}</p>
                            <p class="card-text">{{ book.quantity }} book(s) left</p>

                            {% if book.quantity > 0 %}
                                <form action="{% url 'store:buy_book' book.id %}" class="form" method="post">
                                    {% csrf_token %}

                                    <div class="form-group w-25">
                                        <label for="quantity">Quantity:</label>
                                        <input type="number" class="form-control" name="quantity" id="quantity"
                                               value="0"
                                               min="1" max="{{ book.quantity }}">
                                    </div>

                                    <button type="submit" class="btn btn-success">To Cart
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor"
                                             class="bi bi-cart" viewBox="0 0 16 16" style="transform: translateY(-1px)">
                                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                        </svg>
                                    </button>
                                </form>
                            {% else %}
                                <p>Unavailable...</p>
                            {% endif %}
                        </div>
                    </div>

                    <div class="d-flex mt-1">
                        <label class="ml-2"
                               style="font-weight: bold; margin-top: 10px; font-size: large">Genres:</label>
                        <div aria-label="breadcrumb">
                            <ol class="breadcrumb bg-transparent">
                                {% for category in book.category.all %}
                                    <li class="breadcrumb-item active" aria-current="page"><a
                                            href="#">{{ category }}</a></li>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>

                    <div class="d-flex mt-1">
                        <label class="ml-2"
                               style="font-weight: bold; margin-top: -12px; font-size: large">Year Published
                            First:</label>
                        <p style="margin-top: -10px; margin-left: 10px;">{{ book.first_published }}</p>
                    </div>

                    <div class="ml-2">
                        <label for="description" style="font-weight: bold; font-size: large">Description:</label>
                        <p id="description" name="description">{{ book.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

templates/store/edit_book.html
{% extends "store/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="row">
        <div class="col-5">
            <form action="{% url 'store:edit_book' book.id %}" class="form" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}

                {% buttons %}
                    <button style="width: 130px;" class="btn btn-primary" name="submit">
                        Save</button>
                {% endbuttons %}
            </form>

            <form action="{% url 'store:buy_book' book.id %}" method="post">
                {% csrf_token %}
                {% buttons %}
                    <button style="width: 130px;" class="btn btn-success"
                            onclick="return confirm('Are you sure you want to buy {{ book.id }}?')" name="submit">
                        Buy
                    </button>
                {% endbuttons %}
            </form>
        </div>

        <div class="col-6">
            <img class="image-details m-2" src="{{ book.url }}"
                 alt="Card image cap" title={{ book.title }}>
        </div>
    </div>
{% endblock content %}

templates/store/index.html
{% extends "store/base.html" %}
{% block content %}
    <div class="jumbotron" style="margin-top: 15px; background-color: #B22222; color: white;">
        <h1 class="display-4">Online Book Store</h1>
        <p class="lead">Search for your favorite book, add it to your wish list and buy it.</p>

        {% if user.is_authenticated %}
        {% else %}
            <a class="btn btn-lg btn-danger" href="{% url 'users:register' %}"
               role="button">Register &raquo;</a>
        {% endif %}
    </div>
{% endblock content %}

templates/store/old_cart.html
{% extends "store/cart.html" %}

templates/store/orders.html
{% extends "store/base.html" %}

{% block content %}
    {% for order in orders %}
        <a href="{% url 'store:old_cart' order.cart.id %}">
            <div class="row bg-white m-3 d-flex p-2">
                <p>{{ order.date_added }} &nbsp;|&nbsp;</p>
                <p>Payed: ${{ order.cart.total }} &nbsp;|&nbsp;</p>
                <p>{{ order.contact }}</p>
            </div>
        </a>
    {% empty %}
        <p>No orders available...</p>
    {% endfor %}
{% endblock content %}